Add script to update accelerators in GLPI
redhat-eets/glpi-helper-scripts pull request #114
Opened 2024-12-21 01:55 UTC by adhil0

This script goes through every machine in GLPI and updates its accelerators.

2025-01-09 21:47 UTC, dkosteck approved these changes
So this is just to update existing accelerators for existing machines in GLPI vs the other PR which adds them at import as well?

2025-01-09 21:50 UTC, dkosteck requested changes
Linter needs addressing actually,

2025-01-09 23:03 UTC, adhil0 commented
> So this is just to update existing accelerators for existing machines in GLPI vs the other PR which adds them at import as well?

Correct

2025-01-10 14:07 UTC, dkosteck approved these changes
Looks good, thanks

2025-01-10 22:26 UTC, merged