updated help text to specify which token to be used in script help text
redhat-eets/glpi-helper-scripts pull request #34
Opened 2023-07-19 19:30 UTC by ericz2002

2023-07-19 19:48 UTC, dkosteck requested changes
Thanks! Can you also update https://github.com/redhat-eets/glpi-helper-scripts/blob/eacaeb8dbd2125fbe1f77fd4fd77b62d8465917f/README.md?plain=1#L195 and the line underneath that references the token to state that it's the "GLPI API Token" and not just "GLPI Token", essentially take a pass through the README and see if it's consistently referencing the API token?

2023-07-20 19:26 UTC, dkosteck requested changes
I think there's one more place in the README with GLPI TOKEN

2023-07-20 20:02 UTC, dkosteck approved these changes
Looks good, thanks

2023-07-20 20:18 UTC, adhil0 approved these changes

2023-07-21 17:40 UTC, merged